# Generated by Django 3.1.5 on 2021-01-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id_day', models.IntegerField(primary_key=True, serialize=False)),
                ('day_ru', models.CharField(max_length=50)),
                ('sunrise', models.CharField(max_length=25)),
                ('sunset', models.CharField(max_length=20)),
                ('true_noon', models.CharField(max_length=20)),
                ('daylight_hours', models.CharField(max_length=30)),
                ('month_str', models.CharField(max_length=30)),
                ('day_int', models.IntegerField()),
                ('month_int', models.IntegerField()),
            ],
        ),
    ]
